# Generated by Django 5.2.18 on 2026-10-08 17:16

import django.db.models.deletion
import providers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('tourist', 'Tourist'), ('hotel_owner', 'Hotel & Accommodation Manager'), ('tour_operator', 'Tour Guide / Tour Operator'), ('artisan', 'Artisan'), ('restaurant_owner', 'Restaurant Manager'), ('transport_owner', 'Transport Provider'), ('park_manager', 'Park Manager'), ('destination_manager', 'Destination Manager'), ('history_culture_manager', 'History & Culture Manager'), ('shop_owner', 'Shop & Market Manager'), ('spa_manager', 'Massage & Spa Manager'), ('admin', 'Administrator')], max_length=32)),
                ('service_type', models.CharField(choices=[('destination', 'Destination'), ('hotel', 'Hotel'), ('park', 'Park'), ('restaurant', 'Restaurant'), ('transport', 'Transport'), ('spa', 'Massage & Spa'), ('artisan', 'Artisan'), ('history-culture', 'History & Culture'), ('shop', 'Shop')], db_index=True, max_length=32)),
                ('company_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('hours', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('image', models.CharField(blank=True, max_length=500)),
                ('linked_listing_id', models.PositiveIntegerField(default=1, help_text='Public listing (same service type) this workspace manages')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('price_label', models.CharField(blank=True, max_length=60)),
                ('image', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('paused', 'Paused')], default='draft', max_length=10)),
                ('schedule_mode', models.CharField(choices=[('overnight', 'Overnight'), ('day_visit', 'Day visit'), ('order', 'Order')], default='day_visit', max_length=12)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('available_count', models.IntegerField(blank=True, null=True)),
                ('total_count', models.IntegerField(blank=True, null=True)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('beds', models.CharField(blank=True, max_length=100)),
                ('size_sqm', models.PositiveIntegerField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog', to='providers.providerworkspace')),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityRule',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('item_id', models.CharField(default='all', max_length=64)),
                ('blocked_dates', models.JSONField(blank=True, default=list)),
                ('limited_dates', models.JSONField(blank=True, default=list)),
                ('open_time_slots', models.JSONField(blank=True, default=providers.models.default_time_slots)),
                ('closed_time_slots', models.JSONField(blank=True, default=list)),
                ('capacity_per_day', models.PositiveIntegerField(default=4)),
                ('notes', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='providers.providerworkspace')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddConstraint(
            model_name='providerworkspace',
            constraint=models.UniqueConstraint(fields=('user', 'role'), name='one_workspace_per_user_role'),
        ),
    ]
