# Generated by Django 5.2.18 on 2026-10-08 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('shift', models.CharField(blank=True, help_text='e.g. "Morning 06:00–14:00"', max_length=60)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On leave'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('hired_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='providers.providerworkspace')),
            ],
            options={
                'ordering': ['department', 'name'],
            },
        ),
    ]
