# Generated by Django 5.2.18 on 2026-10-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('data', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'reference data',
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('destination', 'Destination'), ('hotel', 'Hotel'), ('park', 'Park'), ('restaurant', 'Restaurant'), ('transport', 'Transport'), ('spa', 'Massage & Spa'), ('artisan', 'Artisan'), ('history-culture', 'History & Culture'), ('shop', 'Shop')], db_index=True, max_length=32)),
                ('listing_id', models.PositiveIntegerField(help_text='Public id used in frontend URLs, e.g. /hotels/3')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('province', models.CharField(blank=True, db_index=True, max_length=100)),
                ('image', models.CharField(blank=True, max_length=500)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('reviews', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['service_type', 'listing_id'],
                'constraints': [models.UniqueConstraint(fields=('service_type', 'listing_id'), name='unique_listing_per_type')],
            },
        ),
    ]
