# Generated by Django 5.2.18 on 2026-10-08 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='base_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='listing',
            name='base_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('destination', 'Destination'), ('hotel', 'Hotel'), ('park', 'Park'), ('restaurant', 'Restaurant'), ('transport', 'Transport'), ('spa', 'Massage & Spa'), ('artisan', 'Artisan'), ('history-culture', 'History & Culture'), ('shop', 'Shop')], max_length=32)),
                ('listing_id', models.PositiveIntegerField()),
                ('facility_id', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('room', 'Room'), ('service', 'Service'), ('product', 'Product'), ('treatment', 'Treatment'), ('facility', 'Facility')], default='facility', max_length=16)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='USD. Empty = use the listing base price.', max_digits=12, null=True)),
                ('price_label', models.CharField(blank=True, max_length=60)),
                ('image', models.CharField(blank=True, max_length=500)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Max guests per booking/slot', null=True)),
                ('inventory', models.PositiveIntegerField(blank=True, help_text='Rooms/vehicles of this type', null=True)),
                ('stock', models.IntegerField(blank=True, help_text='Products only; empty = unlimited', null=True)),
            ],
            options={
                'verbose_name_plural': 'facilities',
                'ordering': ['service_type', 'listing_id', 'facility_id'],
                'constraints': [models.UniqueConstraint(fields=('service_type', 'listing_id', 'facility_id'), name='unique_facility_per_listing')],
            },
        ),
        migrations.CreateModel(
            name='TripPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.JSONField(default=dict)),
                ('plan', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
