# Generated by Django 5.2.18 on 2026-10-08 17:16

import accounts.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('tourist', 'Tourist'), ('hotel_owner', 'Hotel & Accommodation Manager'), ('tour_operator', 'Tour Guide / Tour Operator'), ('artisan', 'Artisan'), ('restaurant_owner', 'Restaurant Manager'), ('transport_owner', 'Transport Provider'), ('park_manager', 'Park Manager'), ('destination_manager', 'Destination Manager'), ('history_culture_manager', 'History & Culture Manager'), ('shop_owner', 'Shop & Market Manager'), ('spa_manager', 'Massage & Spa Manager'), ('admin', 'Administrator')], default='tourist', max_length=32)),
                ('avatar', models.URLField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['email'],
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
