# Generated by Django 5.2.18 on 2026-10-08 17:58

from django.db import migrations, models


def verify_existing_accounts(apps, schema_editor):
    """Accounts created before email verification existed are treated as verified."""
    apps.get_model('accounts', 'User').objects.update(email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.RunPython(verify_existing_accounts, migrations.RunPython.noop),
    ]
