# Generated by Django 5.2.18 on 2026-10-08 17:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_booking_amount_refunded_booking_archived_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('destination', 'Destination'), ('hotel', 'Hotel'), ('park', 'Park'), ('restaurant', 'Restaurant'), ('transport', 'Transport'), ('spa', 'Massage & Spa'), ('artisan', 'Artisan'), ('history-culture', 'History & Culture'), ('shop', 'Shop')], db_index=True, max_length=32)),
                ('listing_id', models.PositiveIntegerField(db_index=True)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, max_length=120)),
                ('comment', models.TextField(max_length=3000)),
                ('reply', models.TextField(blank=True, max_length=3000)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service_type', 'listing_id', 'is_published'], name='reviews_rev_service_aa14f2_idx')],
            },
        ),
    ]
