# Generated by Django 5.2.18 on 2026-10-08 17:16

import bookings.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.CharField(default=bookings.models.booking_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=32, unique=True)),
                ('service_type', models.CharField(choices=[('destination', 'Destination'), ('hotel', 'Hotel'), ('park', 'Park'), ('restaurant', 'Restaurant'), ('transport', 'Transport'), ('spa', 'Massage & Spa'), ('artisan', 'Artisan'), ('history-culture', 'History & Culture'), ('shop', 'Shop')], db_index=True, max_length=32)),
                ('service_id', models.CharField(help_text='Listing id, or "<listing>:<facility>"', max_length=120)),
                ('listing_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('service_name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('image', models.CharField(blank=True, max_length=500)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('time_slot', models.CharField(blank=True, max_length=16)),
                ('guests', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('guest_full_name', models.CharField(max_length=150)),
                ('guest_email', models.EmailField(db_index=True, max_length=254)),
                ('guest_phone', models.CharField(blank=True, max_length=40)),
                ('special_requests', models.TextField(blank=True)),
                ('payment_type', models.CharField(choices=[('full', 'Full'), ('partial', 'Partial')], max_length=16)),
                ('payment_method', models.CharField(choices=[('card', 'Card'), ('mobile_money', 'Mobile money'), ('bank_transfer', 'Bank transfer')], max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=16)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposit_percent', models.PositiveSmallIntegerField(default=30)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], db_index=True, default='pending_payment', max_length=20)),
                ('fulfillment', models.CharField(blank=True, choices=[('not_started', 'Not started'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('in_service', 'In service'), ('fulfilled', 'Fulfilled')], max_length=20, null=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(default=bookings.models.notification_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('booking', 'Booking'), ('payment', 'Payment'), ('checkin', 'Check-in'), ('checkout', 'Check-out'), ('reminder', 'Reminder'), ('system', 'System')], default='system', max_length=16)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='bookings.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['service_type', 'listing_id', 'check_in'], name='bookings_bo_service_96c820_idx'),
        ),
    ]
